name: arxeps
channels:
  - nodefaults
  - conda-forge
dependencies:
  - makim
  - pip
  - python
  - pip:
    - mkdocs >=1.4.3
    - mkdocs-exclude >=1.0.2
    - mkdocs-jupyter >=0.24.7
    - mkdocs-literate-nav >=0.6.0
    - mkdocs-macros-plugin >=0.7.0,<1
    - mkdocs-material >=9.1.15
    - mkdocstrings[python] >=0.24.3
    - makim == 1.27.0
    - jupyterlab >=4.0.7
    - mkdocs-gen-files >=0.5.0
